# Generated by Django 2.2.2 on 2019-06-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='resetTime',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='sendUserEmail',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resetFlag',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sendEmailFlag',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enjoy_company',
            field=models.DateField(blank=True, null=True, verbose_name='进集团日期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enjoy_wgt',
            field=models.DateField(blank=True, null=True, verbose_name='进WGT日期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(default=0, max_length=20, verbose_name='分类'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='relContent',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='发布内容'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(choices=[('unit', '部门'), ('department', '小组')], default='department', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Structure', verbose_name='小组'),
        ),
    ]
