# Generated by Django 2.2.2 on 2019-09-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190621_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.CharField(blank=True, max_length=60, null=True, verbose_name='配件平台')),
            ],
            options={
                'verbose_name': '配件信息',
                'verbose_name_plural': '配件信息',
            },
        ),
    ]
