# Generated by Django 2.2.2 on 2019-09-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20190907_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time_control',
            field=models.CharField(choices=[('1', '管控'), ('2', '不管控')], default='1', max_length=30, verbose_name='加班管控'),
        ),
    ]
