# Generated by Django 2.2.2 on 2019-09-28 15:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_userprofile_time_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('comments', models.CharField(max_length=30, verbose_name='备注')),
                ('publisher', models.CharField(max_length=30, verbose_name='发布者')),
                ('desc_pack', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='测试说明内容')),
            ],
            options={
                'verbose_name': '测试说明书',
                'verbose_name_plural': '测试说明书',
            },
        ),
    ]
