# Generated by Django 2.2.2 on 2019-09-28 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_testword'),
    ]

    operations = [
        migrations.AddField(
            model_name='testword',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
