# Generated by Django 2.2.2 on 2019-10-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_testword_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='relContent',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='发布内容'),
        ),
    ]
