# Generated by Django 2.2.2 on 2019-08-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskArrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wgt_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='WGT No.')),
                ('serial_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Serial No')),
                ('fused', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fused')),
                ('nand', models.CharField(blank=True, max_length=30, null=True, verbose_name='NAND')),
                ('test_build', models.CharField(blank=True, max_length=30, null=True, verbose_name='Test Build')),
                ('tester', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tester')),
            ],
            options={
                'verbose_name': '测试安排',
                'verbose_name_plural': '测试安排',
            },
        ),
    ]
