# Generated by Django 2.2.2 on 2019-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testManage', '0002_taskarrange_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskarrange',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comments'),
        ),
    ]
