# Generated by Django 2.2.2 on 2019-08-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testManage', '0003_auto_20190826_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeArrange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '时间安排',
                'verbose_name_plural': '时间安排',
            },
        ),
    ]
