# Generated by Django 2.2.2 on 2019-08-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testManage', '0004_timearrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskarrange',
            name='task_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testManage.TimeArrange', verbose_name='安排时间'),
        ),
    ]
