# Generated by Django 2.2.2 on 2019-08-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testManage', '0005_taskarrange_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timearrange',
            name='pub_date',
            field=models.DateField(verbose_name='发布时间'),
        ),
    ]
