# Generated by Django 2.2.2 on 2019-09-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testManage', '0006_auto_20190829_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='登记日期')),
                ('group', models.CharField(blank=True, max_length=30, null=True, verbose_name='提报小组')),
                ('find_per', models.CharField(blank=True, max_length=30, null=True, verbose_name='发现人')),
                ('sub_per', models.CharField(blank=True, max_length=30, null=True, verbose_name='提报人')),
                ('radar_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='雷达ID')),
                ('desc', models.CharField(blank=True, max_length=30, null=True, verbose_name='描述')),
                ('comments', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '测试安排',
                'verbose_name_plural': '测试安排',
            },
        ),
    ]
