# Generated by Django 2.2.2 on 2019-08-02 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abnormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyNum', models.CharField(blank=True, max_length=30, null=True, verbose_name='申請單號')),
                ('apply_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='申请时间')),
                ('leave_type', models.CharField(choices=[('1', '事假'), ('2', '路程假'), ('3', '專案事假'), ('4', '年休假'), ('5', '產假'), ('6', '返鄉福利假'), ('7', '婚假'), ('8', '病假'), ('9', '喪假'), ('10', '三八婦女節假')], default='1', max_length=20, verbose_name='是否长借')),
                ('startTime', models.CharField(blank=True, max_length=30, null=True, verbose_name='开始工作日')),
                ('endTime', models.CharField(blank=True, max_length=30, null=True, verbose_name='结束工作日')),
                ('leave_start_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='请假开始时间')),
                ('leave_end_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='请假结束时间')),
                ('time_start_period', models.CharField(blank=True, max_length=30, null=True, verbose_name='请假开始时间段')),
                ('time_end_period', models.CharField(blank=True, max_length=30, null=True, verbose_name='请假结束时间段')),
                ('reason', models.CharField(blank=True, max_length=80, null=True, verbose_name='请假原因')),
                ('agent_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='代理人姓名')),
                ('agent_worknum', models.CharField(blank=True, max_length=80, null=True, verbose_name='代理人工号')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户姓名')),
            ],
            options={
                'verbose_name': '请假申请单',
                'verbose_name_plural': '请假申请单',
            },
        ),
    ]
