# Generated by Django 2.2.2 on 2019-08-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyNum', models.CharField(blank=True, max_length=30, null=True, verbose_name='申請單號')),
                ('applyUser', models.CharField(blank=True, max_length=30, null=True, verbose_name='申請人')),
                ('applyUnit', models.CharField(blank=True, max_length=30, null=True, verbose_name='申請單位')),
                ('applyType', models.CharField(blank=True, max_length=30, null=True, verbose_name='申請类别')),
                ('applyDate', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('applyState', models.CharField(blank=True, choices=[('1', '待簽核'), ('2', '已簽核'), ('3', '已取消')], default='1', max_length=30, verbose_name='申請狀態')),
                ('applyRemark', models.CharField(blank=True, max_length=30, null=True, verbose_name='申请单備註')),
            ],
            options={
                'verbose_name': '申請單',
                'verbose_name_plural': '申請單',
            },
        ),
        migrations.RemoveField(
            model_name='abnormal',
            name='applyNum',
        ),
        migrations.AddField(
            model_name='abnormal',
            name='lengh_time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='请假时长'),
        ),
        migrations.AddField(
            model_name='abnormal',
            name='fk_apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='overtime.ApplyList', verbose_name='申請單號'),
        ),
    ]
