# Generated by Django 2.2.2 on 2019-08-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_auto_20190803_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='applyType',
            field=models.CharField(blank=True, choices=[('1', '请假'), ('2', '异常'), ('3', '加班')], max_length=30, null=True, verbose_name='申請类别'),
        ),
    ]
