# Generated by Django 2.2.2 on 2019-08-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0004_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='fk_apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overtime.ApplyList', verbose_name='申請單號'),
        ),
    ]
