# Generated by Django 2.2.2 on 2019-08-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0005_auto_20190803_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='confirmUser',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='确认人'),
        ),
    ]
