# Generated by Django 2.2.2 on 2019-08-03 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0006_applylist_confirmuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applylist',
            name='applyRemark',
        ),
        migrations.AddField(
            model_name='applylist',
            name='confirmTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='确认時間'),
            preserve_default=False,
        ),
    ]
