# Generated by Django 2.2.2 on 2019-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0007_auto_20190803_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='confirmTime',
            field=models.DateTimeField(verbose_name='确认時間'),
        ),
    ]
