# Generated by Django 2.2.2 on 2019-08-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0008_auto_20190803_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='confirmTime',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='确认时间'),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='confirmUser',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='确认主管'),
        ),
    ]
