# Generated by Django 2.2.2 on 2019-08-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0009_auto_20190803_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='confirmDepartment',
            field=models.CharField(blank=True, default='Leader', max_length=30, null=True, verbose_name='确认單位'),
        ),
    ]
