# Generated by Django 2.2.2 on 2019-08-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0010_applylist_confirmdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='applyState',
            field=models.CharField(blank=True, choices=[('1', '待簽核'), ('2', '已簽核'), ('3', '已取消'), ('4', '以拒绝')], default='1', max_length=30, verbose_name='申請狀態'),
        ),
    ]
