# Generated by Django 2.2.2 on 2019-08-12 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overtime', '0012_timetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.CharField(blank=True, max_length=30, null=True, verbose_name='加班时间')),
                ('data_hour', models.CharField(blank=True, max_length=30, null=True, verbose_name='加班小时')),
                ('data_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='加班类型')),
                ('add_content', models.CharField(blank=True, max_length=100, null=True, verbose_name='加班内容')),
                ('fk_apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overtime.ApplyList', verbose_name='申請單號')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户姓名')),
            ],
            options={
                'verbose_name': '加班申请单',
                'verbose_name_plural': '加班申请单',
            },
        ),
    ]
