# Generated by Django 2.2.2 on 2019-08-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0013_addtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=30, null=True, verbose_name='加班月份')),
            ],
            options={
                'verbose_name': '加班月份',
                'verbose_name_plural': '加班月份',
            },
        ),
        migrations.AlterField(
            model_name='abnormal',
            name='fk_apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overtime.ApplyList', verbose_name='申請單號'),
        ),
        migrations.AddField(
            model_name='applylist',
            name='fk_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overtime.AddMonth', verbose_name='加班月份'),
        ),
    ]
