# Generated by Django 2.2.2 on 2019-08-14 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0014_auto_20190814_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtime',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户姓名'),
        ),
    ]
