# Generated by Django 2.2.2 on 2019-08-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0015_auto_20190814_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetype',
            name='tscale',
            field=models.CharField(default='0.3', max_length=30, verbose_name='周加班比例'),
        ),
    ]
