# Generated by Django 2.2.2 on 2019-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0016_timetype_tscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetype',
            name='tdate',
            field=models.CharField(default='25', max_length=30, verbose_name='提报加班日期'),
        ),
    ]
