# Generated by Django 2.2.2 on 2019-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0017_timetype_tdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='applyDate',
            field=models.DateTimeField(verbose_name='申請時間'),
        ),
    ]
