# Generated by Django 2.2.2 on 2019-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdetails',
            name='date_out',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Date out'),
        ),
    ]
