# Generated by Django 2.2.2 on 2019-10-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqe', '0002_auto_20191019_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddetails',
            name='date_out',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='出库日期'),
        ),
    ]
