# Generated by Django 2.2.2 on 2019-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqe', '0003_auto_20191019_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylistdetail',
            name='lendDate',
            field=models.DateTimeField(verbose_name='确认時間'),
        ),
    ]
