# Generated by Django 2.2.2 on 2019-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqe', '0004_auto_20191024_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylistdetail',
            name='lendDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认時間'),
        ),
    ]
