# Generated by Django 2.2.2 on 2019-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqe', '0005_auto_20191024_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylistdetail',
            name='applyDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申请时间'),
        ),
    ]
