# Generated by Django 2.2.2 on 2019-10-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqe', '0006_applylistdetail_applydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorylistdetail',
            name='applyDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='accessorylistdetail',
            name='lendDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认時間'),
        ),
    ]
